#!/bin/sh
set -eu

report="traceability-report.md"

if [ ! -d specs/functional ]; then
  echo "traceability_check: OK (no specs/functional directory; template state)"
  exit 0
fi

feature_files=$(find specs/functional -type f -name "*.feature" 2>/dev/null || true)
if [ -z "$feature_files" ]; then
  echo "ERROR: No .feature files found to extract FSIDs." >&2
  exit 1
fi

fsids=$(grep -ho "FS-[A-Z0-9-]\{3,\}-[0-9]\{3\}" $feature_files | sort -u)
if [ -z "$fsids" ]; then
  echo "ERROR: No FSIDs found in functional specs." >&2
  exit 1
fi

search_dirs="tests/acceptance"
missing=0

{
  echo "# Traceability Report"
  echo ""
  echo "Generated by tools/traceability/traceability_check.sh"
  echo ""
  echo "| FSID | References | Status |"
  echo "| --- | --- | --- |"

  for fsid in $fsids; do
    refs=$(grep -rl "$fsid" $search_dirs 2>/dev/null || true)
    if [ -n "$refs" ]; then
      ref_list=$(echo "$refs" | tr '\n' ',' | sed 's/, $//; s/,$//')
      echo "| $fsid | $ref_list | OK |"
    else
      echo "| $fsid | none | MISSING |"
      missing=1
    fi
  done
} > "$report"

if [ "$missing" -ne 0 ]; then
  echo "ERROR: Some FSIDs are missing in acceptance tests. See $report." >&2
  exit 1
fi

echo "traceability_check: OK"
